### ISSUE TITLE
When will the draft be finalized?

### ISSUE THREAD

**Issue by AusIV** [0xProject/standard-relayer-api#16]
At OpenRelay we'd really like to target the standard-relayer-api, but we don't want to spin our wheels chasing a specification that's changing every couple of days. Given that the API is versioned anyway, can we get a timeline for locking down a final /v0/ API, and have any subsequent breaking changes go into a /v1/ draft?

**Comment by willwarren89** [comment]
Now that the v0 draft has been [announced publicly](https://blog.0xproject.com/introducing-the-0x-standard-relayer-api-8a37bd90a3e), I think it makes sense to leave ~1 week for feedback prior to locking it down.
