### ISSUE TITLE
Is order filling/cancelling part of standard-relayer-api?

### ISSUE THREAD

**Issue by qibinlou** [0xProject/standard-relayer-api#24]
Hi @BMillman19 @fabioberger great work on the 0xProject at first! I am trying to build my relayer on top of 0x's standard-relayer-api and I found out that order filling/cancelling is not part of the standard but we do have order filling/cancelling schema tests here https://github.com/0xProject/0x-monorepo/blame/development/packages/json-schemas/test/schema_test.ts#L280. 

I am wondering is that going into the standard or it leaves to relayer to implement their customized apis. Thanks!

**Comment by fabioberger** [comment]
@qibinlou for open orderbook relayers, users take orders and fill/cancel them directly on Ethereum. They do not do these actions through the relayer. If you are building a matching relayer, you would implement your own API endpoints for filling.
