### ISSUE TITLE
Validations to put on /0x/v0/order POST

### ISSUE THREAD

**Issue by rhrahul** [0xProject/standard-relayer-api#27]
Hey,

I am not sure what radarrelay standard API is using to validate POST order/ endpoint.
can you assist me with that, I understood every other endpoints using json-schemas.
But radarrelay is giving you perfect output of what the error is, how to do that ?
Please suggest me.

Thanks

**Comment by LogvinovLeon** [comment]
They just wrote a bunch of custom logic

**Comment by rhrahul** [comment]
Ok, thanks 👍

**Comment by rhrahul** [comment]
Ok thanks
