### ISSUE TITLE
Fee API Rigidity

### ISSUE THREAD

**Issue by AusIV** [0xProject/standard-relayer-api#6]
I have a few thoughts about the fee API.

The API seems to assume a greater rigidity of fee structure than I think is appropriate. A relayer might give makers some leeway regarding how much of the fee is paid by the maker, and how much is paid by the taker, leaving it to the market to determine an allocation of fees. The current fee API only allows the relayer to specify a single option for fees, but if the fee API returned a list instead of a single object the relayer could specify several acceptable fees. It may not be feasible to enumerate all possible fees, or to have the API define a set of rules for choosing an acceptable fee, but I at least think it should be possible to return more than a single acceptable fee. If the response type is a list, relayers that want to rigidly define the fee structure can return only one option, while relayers that want to allow flexibility could return several example of acceptable fees.

**Comment by abandeali1** [comment]
I think the most flexible way to deal with this would be to have `minTotalFee`, `minMakerFee`, and `minTakerFee` fields in the fee endpoint response. 

I'm not convinced this is necessary, though. When would a maker ever not want to pay the minimum fee?

**Comment by AusIV** [comment]
If there's a market for trades, a maker can make their offer more attractive than the next by picking up a bigger share of the fees despite having the same exchange rate. You may be right that makers will always shift fees to the taker, but I think the protocol at least ought to leave room for relays to run an experiment (otherwise the relays may just ignore the standard API and specific their own).

**Comment by abandeali1** [comment]
I think in that particular case the maker would probably compete on price rather than fees, but I do see how they are not quite the same. I think there's also value in a relayer providing a max fee to prevent spam orders (orders with fees so large that they are essentially infillable). 

Returning `minTotalFee`, `maxTotalFee`, `minMakerFee`, and `minTakerFee` makes the most sense to me.
